# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.2
_src_path: git@github.com:actuaristai/template.git
email: ''
full_name: Actuarist AI
project_name: python_articles
project_short_description: Repository for publishing useful articles on python and
    data science
remote_repository: git@github.com:actuaristai/python_articles.git
